version: "3.8"

services:
  mongo:
    image: mongo:4.4
    container_name: finmark_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: # Keeps data safe even if the container stops
